PRAGMA foreign_keys=1;
BEGIN;
INSERT INTO user_parameter VALUES('tortuosity','crop',NULL,0.002,0.002,0.002);
INSERT INTO user_parameter VALUES('canopy_reflection_coefficient','crop',NULL,0.08,0.08,0.08);
INSERT INTO user_parameter VALUES('reference_max_assimilation_rate','crop','',30.0,30.0,30.0);
INSERT INTO user_parameter VALUES('reference_leaf_area_index','crop','',1.44,1.44,1.44);
INSERT INTO user_parameter VALUES('maintenance_respiration_parameter_2','crop','',44.0,44.0,44.0);
INSERT INTO user_parameter VALUES('maintenance_respiration_parameter_1','crop','',0.08,0.08,0.08);
INSERT INTO user_parameter VALUES('minimum_n_concentration_root','crop','[kg kg-1]',0.005,0.005,0.005);
INSERT INTO user_parameter VALUES('minimum_available_n','crop','[kg m-2] default: 0.000075',7.5e-05,0.00075,0.00075);
INSERT INTO user_parameter VALUES('reference_albedo','crop / soil_moisture','',0.23,0.23,0.23);
INSERT INTO user_parameter VALUES('stomata_conductance_alpha','crop','',40.0,40.0,40.0);
INSERT INTO user_parameter VALUES('saturation_beta','crop','',2.5,2.5,2.5);
INSERT INTO user_parameter VALUES('growth_respiration_redux','crop','',0.7,0.7,0.7);
INSERT INTO user_parameter VALUES('max_crop_n_demand','crop','',6.0,6.0,6.0);
INSERT INTO user_parameter VALUES('growth_respiration_parameter_2','crop','',38.0,38.0,38.0);
INSERT INTO user_parameter VALUES('growth_respiration_parameter_1','crop','',0.1,0.1,0.1);
INSERT INTO user_parameter VALUES('use_automatic_irrigation','environment','boolean',0.0,0.0,0.0);
INSERT INTO user_parameter VALUES('use_nmin_mineral_fertilising_method','environment','boolean',0.0,0.0,0.0);
INSERT INTO user_parameter VALUES('layer_thickness','environment','[m]',0.1,0.1,0.1);
INSERT INTO user_parameter VALUES('number_of_layers','environment','',20.0,20.0,20.0);
INSERT INTO user_parameter VALUES('start_pv_index','environment','',0.0,0.0,0.0);
INSERT INTO user_parameter VALUES('albedo','environment','',0.23,0.2,0.23);
INSERT INTO user_parameter VALUES('athmospheric_co2','environment','[ppm]',0.0,0.0,0.0);
INSERT INTO user_parameter VALUES('wind_speed_height','environment','[m]',2.0,2.0,2.0);
INSERT INTO user_parameter VALUES('use_secondary_yields','environment','boolean',1.0,1.0,1.0);
INSERT INTO user_parameter VALUES('julian_day_automatic_fertilising','environment','31 + 28 + 15',74.0,74.0,74.0);
INSERT INTO user_parameter VALUES('critical_moisture_depth','soil_column','Lower boundary for irrigation trigger [m]',0.3,0.3,0.3);
INSERT INTO user_parameter VALUES('saturated_hydraulic_conductivity','soil_moisture','[mm d-1]',8640.0,8640.0,8640.0);
INSERT INTO user_parameter VALUES('surface_roughness','soil_moisture','[m]',0.02,0.02,0.02);
INSERT INTO user_parameter VALUES('hydraulic_conductivity_redux','soil_moisture','',0.1,0.1,0.1);
INSERT INTO user_parameter VALUES('snow_accumulation_treshold_temperature','soil_moisture','Upper temperature limit of snow accumulation',1.8,1.8,1.8);
INSERT INTO user_parameter VALUES('kc_factor','soil_moisture','',0.75,0.6,0.75);
INSERT INTO user_parameter VALUES('time_step','environment','[d]',1.0,1.0,1.0);
INSERT INTO user_parameter VALUES('temperature_limit_for_liquid_water','soil_moisture','Lower temperature limit of liquid water in snow',-3.0,-3.0,-3.0);
INSERT INTO user_parameter VALUES('correction_snow','soil_moisture','Correction factor for snow (value used in COUP by Lars Egil H.)',1.14,1.14,1.14);
INSERT INTO user_parameter VALUES('correction_rain','soil_moisture','Correction factor for rain (no correction used here)',1.0,1.0,1.0);
INSERT INTO user_parameter VALUES('snow_max_additional_density','soil_moisture','Maximum additional density of snow (max rho = 0.35, Karvonen)',0.25,0.25,0.25);
INSERT INTO user_parameter VALUES('new_snow_density_min','soil_moisture','Minimum density of new snow',0.1,0.1,0.1);
INSERT INTO user_parameter VALUES('snow_retention_capacity_min','soil_moisture','Minimum liquid water retention capacity in snow [mm]',0.05,0.05,0.05);
INSERT INTO user_parameter VALUES('refreeze_parameter_2','soil_moisture','Refreeze exponent (Karvonen''s value)',0.36,0.36,0.36);
INSERT INTO user_parameter VALUES('refreeze_parameter_1','soil_moisture','Refreeze parameter (Karvonen''s value)',1.5,1.5,1.5);
INSERT INTO user_parameter VALUES('refreeze_temperature','soil_moisture','Base temperature for refreeze [°C]',-1.7,-1.7,-1.7);
INSERT INTO user_parameter VALUES('snowmelt_temperature','soil_moisture','Base temperature for snowmelt [°C]',0.31,0.31,0.31);
INSERT INTO user_parameter VALUES('snow_packing','soil_moisture','Snow packing factor (calibrated by Helge Bonesmo)',0.01,0.01,0.01);
INSERT INTO user_parameter VALUES('snow_retention_capacity_max','soil_moisture','Maximum liquid water retention capacity in snow [mm]',0.17,0.17,0.17);
INSERT INTO user_parameter VALUES('evaporation_zeta','soil_moisture','Tiefe für die Berechnung der Bodenevaporation [m]',40.0,40.0,40.0);
INSERT INTO user_parameter VALUES('xsa_critical_soil_moisture','soil_moisture','Das sind die Steuerungsparameter für die Steigung der Entzugsfunktion',0.1,0.1,0.1);
INSERT INTO user_parameter VALUES('maximum_evaporation_impact_depth','soil_moisture','',5.0,5.0,5.0);
INSERT INTO user_parameter VALUES('ntau','soil_temperature','original 0.65',0.65,0.65,0.65);
INSERT INTO user_parameter VALUES('initial_surface_temperature','soil_temperature','[°C]',10.0,5.0,10.0);
INSERT INTO user_parameter VALUES('base_temperature','soil_temperature','Temperatur für die unterste Schicht (durchschnittl. Jahreslufttemperatur)',9.5,9.5,9.5);
INSERT INTO user_parameter VALUES('quartz_raw_density','soil_temperature','[kg m-3]',2650.0,2650.0,2650.0);
INSERT INTO user_parameter VALUES('density_air','soil_temperature','[kg m-3]',1.25,1.25,1.25);
INSERT INTO user_parameter VALUES('density_water','soil_temperature','[kg m-3]',1000.0,1000.0,1000.0);
INSERT INTO user_parameter VALUES('specific_heat_capacity_air','soil_temperature','[J kg-1 K-1]',1005.0,1005.0,1005.0);
INSERT INTO user_parameter VALUES('specific_heat_capacity_quartz','soil_temperature','[J kg-1 K-1]',750.0,750.0,750.0);
INSERT INTO user_parameter VALUES('specific_heat_capacity_water','soil_temperature','[J kg-1 K-1]',4192.0,4192.0,4192.0);
INSERT INTO user_parameter VALUES('soil_albedo','soil_temperature','',0.7,0.7,0.7);
INSERT INTO user_parameter VALUES('dispersion_length','soil_transport','[m]',0.049,0.049,0.049);
INSERT INTO user_parameter VALUES('AD','soil_transport','Factor a in Kersebaum 1989 p.24 for Loess soils',0.002,0.002,0.002);
INSERT INTO user_parameter VALUES('diffusion_coefficient_standard','soil_transport','[m2 d-1]',0.000214,0.000214,0.000214);
INSERT INTO user_parameter VALUES('leaching_depth','environment','[m]',1.6,2.0,1.5);
INSERT INTO user_parameter VALUES('max_percolation_rate','soil_moisture','[mm d-1]',10.0,8.0,10.0);
INSERT INTO user_parameter VALUES('groundwater_discharge','soil_moisture','Daily discharge rate of groundwater body [mm]',3.0,3.0,3.0);
INSERT INTO user_parameter VALUES('density_humus','soil_temperature','[kg m-3]',1300.0,1300.0,1300.0);
INSERT INTO user_parameter VALUES('specific_heat_capacity_humus','soil_temperature','[kg m-3]',1920.0,1920.0,1920.0);
INSERT INTO user_parameter VALUES('soilmoisture_init_value','soil_moisture','%',0.1,0.8,0.8);
INSERT INTO user_parameter VALUES('max_groundwater_depth','environment','Maximum annual depth of groundwater table [m]',18.0,18.0,18.0);
INSERT INTO user_parameter VALUES('min_groundwater_depth','environment','Minimum annual depth of groundwater table [m]',20.0,20.0,20.0);
INSERT INTO user_parameter VALUES('min_groundwater_depth_month','environment','Month in which minimum depth of groundwater table is reached [month]',3.0,3.0,3.0);
INSERT INTO user_parameter VALUES('SOM_SlowDecCoeffStandard','soil_organic','[d-1], Bruun et al. 2003 (4.3e-5)',4.3e-05,4.3e-05,4.3e-05);
INSERT INTO user_parameter VALUES('SOM_FastDecCoeffStandard','soil_organic','[d-1], from DAISY manual (1.4e-4)',0.00014,0.00014,0.00014);
INSERT INTO user_parameter VALUES('SMB_SlowMaintRateStandard','soil_organic','[d-1], from DAISY manual (1.8e-3)',0.001,0.001,0.001);
INSERT INTO user_parameter VALUES('SMB_FastMaintRateStandard','soil_organic','[d-1], from DAISY manual (1.0e-2)',0.01,0.01,0.01);
INSERT INTO user_parameter VALUES('SMB_SlowDeathRateStandard','soil_organic','[d-1], from DAISY manual (1.0e-3)',0.001,0.001,0.001);
INSERT INTO user_parameter VALUES('SMB_FastDeathRateStandard','soil_organic','[d-1], from DAISY manual (1.0e-2)',0.01,0.01,0.01);
INSERT INTO user_parameter VALUES('SMB_UtilizationEfficiency','soil_organic','[], from DAISY manual (0.6)',0.0,0.6,0.6);
INSERT INTO user_parameter VALUES('SOM_SlowUtilizationEfficiency','soil_organic','[], from DAISY manual (0.4)',0.4,0.4,0.4);
INSERT INTO user_parameter VALUES('SOM_FastUtilizationEfficiency','soil_organic','[], from DAISY manual (0.5)',0.5,0.5,0.5);
INSERT INTO user_parameter VALUES('AOM_SlowUtilizationEfficiency','soil_organic','[], from DAISY manual (0.13)',0.4,0.4,0.4);
INSERT INTO user_parameter VALUES('AOM_FastUtilizationEfficiency','soil_organic','[], from DAISY manual original (0.69)',0.1,0.1,0.1);
INSERT INTO user_parameter VALUES('AOM_FastMaxC_to_N','soil_organic','Maximum C to N ratio of added organic matter',1000.0,1000.0,1000.0);
INSERT INTO user_parameter VALUES('PartSOM_Fast_to_SOM_Slow','soil_organic','[], Bruun et al. 2003 (0.3)',0.3,0.3,0.3);
INSERT INTO user_parameter VALUES('PartSMB_Slow_to_SOM_Fast','soil_organic','[], from DAISY manual (0.6)',0.6,0.6,0.6);
INSERT INTO user_parameter VALUES('PartSMB_Fast_to_SOM_Fast','soil_organic','[], from DAISY manual (0.6)',0.6,0.6,0.6);
INSERT INTO user_parameter VALUES('PartSOM_to_SMB_Slow','soil_organic','[], optimised (0.015)',0.015,0.015,0.015);
INSERT INTO user_parameter VALUES('PartSOM_to_SMB_Fast','soil_organic','[], optimised (0.0002)',0.0002,0.0002,0.0002);
INSERT INTO user_parameter VALUES('CN_Ratio_SMB','soil_organic','C to N ratio of soil microbes',6.7,6.7,6.7);
INSERT INTO user_parameter VALUES('LimitClayEffect','soil_organic','[kg kg-1], from DAISY manual (0.25)',0.25,0.25,0.25);
INSERT INTO user_parameter VALUES('AmmoniaOxidationRateCoeffStandard','soil_organic','[d-1], from DAISY manual (0.1)',0.1,0.1,0.1);
INSERT INTO user_parameter VALUES('NitriteOxidationRateCoeffStandard','soil_organic','[d-1], fudged by Florian Stange',0.2,0.2,0.2);
INSERT INTO user_parameter VALUES('TransportRateCoeff','soil_organic','[d-1], from DAISY manual (0.1)',0.1,0.1,0.1);
INSERT INTO user_parameter VALUES('SpecAnaerobDenitrification','soil_organic','[g gas-N g CO2-C-1]',0.1,0.1,0.1);
INSERT INTO user_parameter VALUES('ImmobilisationRateCoeffNO3','soil_organic','[d-1]',0.5,0.5,0.5);
INSERT INTO user_parameter VALUES('ImmobilisationRateCoeffNH4','soil_organic','[d-1]',0.5,0.5,0.5);
INSERT INTO user_parameter VALUES('Denit1','soil_organic','Denitrification parameter',0.2,0.2,0.2);
INSERT INTO user_parameter VALUES('Denit2','soil_organic','Denitrification parameter',0.8,0.8,0.8);
INSERT INTO user_parameter VALUES('Denit3','soil_organic','Denitrification parameter',0.9,0.9,0.9);
INSERT INTO user_parameter VALUES('HydrolysisKM','soil_organic','Urea hydrolysis km value from Tabatabai 1973',0.00334,0.00334,0.00334);
INSERT INTO user_parameter VALUES('ActivationEnergy','soil_organic','from Gould et al. 1973',41000.0,41000.0,41000.0);
INSERT INTO user_parameter VALUES('HydrolysisP1','soil_organic','Urea hydrolysis parameter from Sadeghi et al. 1988',4.259e-12,4.259e-12,4.259e-12);
INSERT INTO user_parameter VALUES('HydrolysisP2','soil_organic','Urea hydrolysis parameter from Sadeghi et al. 1988',1.408e-12,1.408e-12,1.408e-12);
INSERT INTO user_parameter VALUES('AtmosphericResistance','soil_organic','NH3 volatilisation rate modifier  from Sadeghi et al. 1988',0.0025,0.0025,0.0025);
INSERT INTO user_parameter VALUES('N2OProductionRate','soil_organic','[d-1] from Florian Stange',0.015,0.015,0.015);
INSERT INTO user_parameter VALUES('Inhibitor_NH3','soil_organic','[kg N m-3] NH3-induced inhibitor for nitrite oxidation',1.0,1.0,1.0);
COMMIT;
